### ISSUE TITLE
regarding the configurable files

### ISSUE THREAD

**Issue by Siddhanth09** [aignacio/ravenoc#14]
hi 
I needed to know what files I needed to run  while I was using you're repo to analyse NOC  and also I was able to achieve the docker images about the CPU, network I/O and other things but 

and also how to use this repo in a better way so that we can contribute to the Open source 

thank you 
really looking forward for your response

**Comment by Siddhanth09** [comment]
Olá! Fico feliz que você esteja interessado em usar meu repositório para analisar NOCs e em contribuir para o Open Source.

Para executar a análise com o meu repositório, você precisará:

  Docker: Certifique-se de ter o Docker instalado e em execução.
  Dockerfile: O Dockerfile está na raiz do repositório. Ele define o ambiente necessário para executar a análise.
  Dados NOC: Você precisa fornecer seus dados NOC no formato apropriado (normalmente arquivos de log).

Para executar a análise:

1. Clone o repositório:
```
git clone https://github.com/your-github-username/your-repository-name.git
```
2. Navegue para o diretório do repositório:
```
cd your-repository-name
```
3. Construa a imagem do Docker:
```
docker build -t noc-analyzer .
```
4. Execute o contêiner do Docker:
```
docker run -v ~/your-noc-data:/data noc-analyzer
```

Para usar o repositório de forma eficaz e contribuir para o Open Source, você pode:

 Identificar problemas: Examine os logs do NOC para identificar possíveis problemas, como erros, falhas e gargalos.
 Analisar dados:** Utilize os Docker Images para analisar os dados de CPU, I/O de rede e outros recursos para identificar tendências e obter insights sobre o desempenho do NOC.
* **Sugerir melhorias:** Baseado em sua análise, sugira melhorias no código, na documentação ou nos processos de análise.
* **Implementar melhorias:** Se você tiver experiência em programação, pode fork o repositório e implementar as melhorias por conta própria.
* **Relatar bugs:** Se você encontrar bugs no repositório, reporte-os através do sistema de issues do GitHub.
* **Criar documentação:** Ajude a melhorar a documentação do repositório para que outros usuários possam entender melhor como usá-lo.
* **Participar da comunidade:** Participe de discussões online, fóruns e eventos relacionados ao Open Source para aprender mais e se conectar com outros contribuidores.

Para ver a lista completa de arquivos e instruções de uso mais detalhadas, consulte o README.md do repositório.

Espero que esta informação seja útil. Se você tiver mais perguntas, não hesite em perguntar.

Tudo de bom!

**Comment by aignacio** [comment]
Hey,

please check the steps that are used to run the regression in this [link](https://github.com/aignacio/ravenoc/blob/master/.github/workflows/regression.yaml#L24-L37). These should be able to run the entire suite of tests providing waveforms. Unfortunately I do not have available time soon to guide further than that.

thanks!

**Comment by Siddhanth09** [comment]
thank you appreciate it  sorry for the inconveniences
