### ISSUE TITLE
How to use this repo

### ISSUE THREAD

**Issue by Rohit123451** [aignacio/ravenoc#15]
Hello,

I'm looking for guidance on which files are essential when using your repository for NOC analysis. While I've successfully generated Docker images for CPU, network I/O, and other components, I'm eager to understand how to utilize this repository more effectively for contributing to the open source community. Your insights would be greatly appreciated.

Thank you, and I'm eagerly awaiting your response.

**Comment by aignacio** [comment]
Hey,

please check the steps that are used to run the regression in this [link](https://github.com/aignacio/ravenoc/blob/master/.github/workflows/regression.yaml#L24-L37). These should be able to run the entire suite of tests providing waveforms. Unfortunately I do not have available time soon to guide further than that.

thanks!
