### ISSUE TITLE
Implementation on an FPGA

### ISSUE THREAD

**Issue by kutaybulun** [aignacio/ravenoc#16]
Hello!
I want to synthesize this project on an FPGA in Vivado to do research on and understand the behaviour of NoC's , is there any guide that i can follow to do this?
Or is it possible to synthesize this project on an FPGA at all?
Thank you for your hardwork on this project!

**Comment by aignacio** [comment]
Hey @kutaybulun,
you can take the RTL, configure it as you want, and embed it into your flow, as a reference, see how it was done here:
https://github.com/aignacio/mpsoc_example
