### ISSUE TITLE
Does the router use a pipeline structure?

### ISSUE THREAD

**Issue by Alexander-0619** [aignacio/ravenoc#21]

**Comment by Alexander-0619** [comment]
It seems that the router does not employ a pipeline structure. Do you consider that a pipeline structure is conducive to system realization? I also wonder whether the virtual channels in the router have to receive an entire packet before accepting the flit data of another packet?

**Comment by aignacio** [comment]
@Alexander-0619,

I had plans to include a generate of [skid buffers](https://github.com/aignacio/skid_buffer) but didn't have time to implement yet. Also, the `vcs` will preempt the higher priority flits whenever they appear. I'm sick atm but I'll keep track on adding the skid buffers.

**Tasks before closing the issue:**

- [ ] Include generate for skid buffers

**Comment by Alexander-0619** [comment]
Thanks for the update and hope you get well soon.

**Comment by Alexander-0619** [comment]
Hi! @aignacio

I originally wanted to use the skid buffer to connect the input module and output module inside the router because both modules apply the valid-ready mechanism. However, the ready_i signal of input module  is actually affected by the data_o and valid_o of input module . However, for TX applicable to skid buffer, ready_i and valid_o are independent as follow. So skid buffer can only be used to connect input modules and output modules of different routers?
![图片2](https://github.com/user-attachments/assets/735edca2-480e-47e0-924d-9dddd84444c5)

**Comment by aignacio** [comment]
Hey @Alexander-0619,

I still didn't have time to evaluate this, but if I believe the best approach here in my opinion would be to include the skid buffer at the output module (in the generate statements) with parameter set to REG_OUTPUT == 1. This way you break entirely the combinatorial path logic and improve timing.  Meanwhile, if you are having timing issues, I suggest isolating the NoC in its own floorplanning and connecting the AXI slaves through this design [here](https://github.com/aignacio/axi_register_slice). This basically adds slice registers (skid buffer) into the AXI path that should help with timing closure.

**Comment by Alexander-0619** [comment]
Thanks for your advice. I'll try, by the way, how to run [tb of this design](https://github.com/aignacio/axi_register_slice)?

**Comment by aignacio** [comment]
Hey @Alexander-0619,
take a look at the instructions [here](https://github.com/aignacio/axi_register_slice/blob/main/.github/workflows/test.yaml#L34-L51) for instance.

**Comment by Alexander-0619** [comment]
I see. Thx!
