### ISSUE TITLE
What is the interpretation of names  `axi_mosi_if` and `axi_miso_if`

### ISSUE THREAD

**Issue by hughperkins** [aignacio/ravenoc#3]
Hi, 

What is the interpretation of names  `axi_mosi_if` and `axi_miso_if`? Like how should I verbalise `m`, `o`, `s` and `i`? "master output slave input", and "master input slave output"?

**Comment by aignacio** [comment]
As you guessed, MOSI stands for master output slave input and MISO master
input slave output.

**Comment by hughperkins** [comment]
Thanks!
